#!/bin/sh
set -eu

# @getoptions
ENVIRONMENT_TYPES='desktop | container'

parser_definition() {
  setup   REST help:usage -- "Usage: example.sh [options]... [arguments]..." ''
  msg -- 'Options:'
  option  ENVIRONMENT_TYPE  -e --environment-type pattern:"${ENVIRONMENT_TYPES}"  -- "${ENVIRONMENT_TYPES}"
  option  PREFERENCE_PATH   -p --preference-path  validate:file_exists            -- "preference file path"
  disp    :usage            -h --help
}

file_exists() {
  [ -f "${OPTARG}" ] && return 0 || return 1
}
# @end

# @gengetoptions parser -i parser_definition parse
# Generated by getoptions (BEGIN)
# URL: https://github.com/ko1nksm/getoptions (v3.3.0)
ENVIRONMENT_TYPE=''
PREFERENCE_PATH=''
REST=''
parse() {
  OPTIND=$(($#+1))
  while OPTARG= && [ $# -gt 0 ]; do
    case $1 in
      --?*=*) OPTARG=$1; shift
        eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
        ;;
      --no-*|--without-*) unset OPTARG ;;
      -[ep]?*) OPTARG=$1; shift
        eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
        ;;
      -[h]?*) OPTARG=$1; shift
        eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
        OPTARG= ;;
    esac
    case $1 in
      '-e'|'--environment-type')
        set -- "$1" "$@"
        [ ${OPTARG+x} ] && {
          case $1 in --no-*|--without-*) set "noarg" "${1%%\=*}"; break; esac
          [ "${OPTARG:-}" ] && { shift; OPTARG=$2; } || OPTARG='1'
        } || OPTARG=''
        case $OPTARG in desktop | container) ;;
          *) set "pattern:desktop | container" "$1"; break
        esac
        ENVIRONMENT_TYPE="$OPTARG"
        shift ;;
      '-p'|'--preference-path')
        set -- "$1" "$@"
        [ ${OPTARG+x} ] && {
          case $1 in --no-*|--without-*) set "noarg" "${1%%\=*}"; break; esac
          [ "${OPTARG:-}" ] && { shift; OPTARG=$2; } || OPTARG='1'
        } || OPTARG=''
        file_exists || { set -- file_exists:$? "$1" file_exists; break; }
        PREFERENCE_PATH="$OPTARG"
        shift ;;
      '-h'|'--help')
        usage
        exit 0 ;;
      --)
        shift
        while [ $# -gt 0 ]; do
          REST="${REST} \"\${$(($OPTIND-$#))}\""
          shift
        done
        break ;;
      [-]?*) set "unknown" "$1"; break ;;
      *)
        REST="${REST} \"\${$(($OPTIND-$#))}\""
    esac
    shift
  done
  [ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
  case $1 in
    unknown) set "Unrecognized option: $2" "$@" ;;
    noarg) set "Does not allow an argument: $2" "$@" ;;
    required) set "Requires an argument: $2" "$@" ;;
    pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
    notcmd) set "Not a command: $2" "$@" ;;
    *) set "Validation error ($1): $2" "$@"
  esac
  echo "$1" >&2
  exit 1
}
usage() {
cat<<'GETOPTIONSHERE'
Usage: example.sh [options]... [arguments]...

Options:
  -e, --environment-type[=ENVIRONMENT_TYPE] 
                              desktop | container
  -p, --preference-path[=PREFERENCE_PATH] 
                              preference file path
  -h, --help                  
GETOPTIONSHERE
}
# Generated by getoptions (END)
# @end

parse "$@"
eval "set -- $REST"

echo "ENVIRONMENT_TYPE: $ENVIRONMENT_TYPE, PREFERENCE_PATH: $PREFERENCE_PATH"
printf '%s\n' "$@" # rest arguments
