{ config, pkgs, pkgs-unfree, ... }:

{
  home.packages = [
    pkgs-unfree.claude-code
    pkgs.neovim
    pkgs.direnv
    pkgs.git
    pkgs.lsd
    pkgs.bat
    pkgs.fd
    pkgs.delta
    pkgs.fzf
    pkgs.zinit
    pkgs.zsh-fzf-tab
    pkgs.zsh-completions
    pkgs.zsh-history-search-multi-word
    pkgs.zsh-fast-syntax-highlighting
  ];

  shell.hooks.entries = [
    {
      loader = "main";
      priority = 10;
      source = ../shell-hook-sources/zsh/zinit.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../shell-hook-sources/zsh/envvar.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../shell-hook-sources/zsh/option.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../shell-hook-sources/zsh/keybind.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../shell-hook-sources/common/lsd.sh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../shell-hook-sources/common/delta.sh;
    }
    {
      loader = "postload";
      priority = 90;
      source = ../shell-hook-sources/zsh/direnv.zsh;
    }
  ];

  home.file.".zshrc".text = ''
    # generated by home-manager

    # interactive only
    [[ -o interactive ]] || return

    # load shell hooks
    if [ -r "${config.xdg.configHome}/${config.shell.hooks.scriptPath}" ]; then
      source "${config.xdg.configHome}/${config.shell.hooks.scriptPath}"
    else
      printf 'failed to load shell hook script: not found: "%s" load error.\n' "${config.xdg.configHome}/${config.shell.hooks.scriptPath}" >&2
    fi
  '';
}
