{ lib, config, ... }:

let
  types = lib.types;
  hooks = config.shell.hooks;
in
{
  options.shell.hooks = {
    baseDir = lib.mkOption {
      type = types.str;
      default = "home-manager/shell-hooks";
      description = "Base directory under XDG_CONFIG_HOME";
    };

    scriptPath = lib.mkOption {
      type = types.str;
      default = "${hooks.baseDir}/hook.sh";
      description = "Hook script path under XDG_CONFIG_HOME";
    };

    loaders = lib.mkOption {
      type = types.attrsOf types.str;
      readOnly = true;
      default = {
        preload  = "preload.d";
        main     = "main.d";
        postload = "postload.d";
      };
      description = "Loader directory mapping";
    };

    entries = lib.mkOption {
      type = types.listOf (types.submodule {
        options = {
          loader = lib.mkOption {
            type = types.enum [ "preload" "main" "postload" ];
            description = "Load phase";
          };

          priority = lib.mkOption {
            type = types.int;
            default = 50;
            description = "Load priority (lower loads earlier)";
          };

          source = lib.mkOption {
            type = types.path;
            description = "Source file to be sourced by shell";
          };
        };
      });
      default = [];
    };
  };

  config = {
    xdg.configFile = lib.mkMerge [
      # create symlinks
      (lib.mkMerge (map
        (entry: let
          dir = "${hooks.baseDir}/${entry.loader}.d";
          name = lib.fixedWidthNumber 2 entry.priority + "-" + baseNameOf entry.source;
        in
        {
          "${dir}/${name}".source = entry.source;
        })
        hooks.entries
      ))

      # generate hook.sh
      {
        "${hooks.scriptPath}".text = ''
          # auto-generated by home-manager (shell-hooks)
          # expected apply example (in .bashrc or .zshrc) : . "${config.xdg.configHome}/${hooks.scriptPath}"

          load_dir() {
            dir="$1"
            [ -d "$dir" ] || return 0

            for f in "$dir"/*; do
              [ -r "$f" ] || continue
              . "$f"
            done
          }

          load_dir "${config.xdg.configHome}/${hooks.baseDir}/preload.d"
          load_dir "${config.xdg.configHome}/${hooks.baseDir}/main.d"
          load_dir "${config.xdg.configHome}/${hooks.baseDir}/postload.d"
        '';
      }
    ];
  };
}
