{ config, pkgs, ... }:

let
  zshFzfTabWithoutModule = pkgs.runCommand "zsh-fzf-tab-without-module" { } ''
    cp -r ${pkgs.zsh-fzf-tab}/share/fzf-tab "$out"
    chmod -R u+w "$out"
    rm -f "$out"/modules/Src/aloxaf/fzftab.so "$out"/modules/Src/aloxaf/fzftab.bundle
  '';
in

{
  home.packages = [
    pkgs.neovim
    pkgs.direnv
    pkgs.git
    pkgs.gh
    pkgs.uutils-coreutils-noprefix
    pkgs.lsd
    pkgs.bat
    pkgs.fd
    pkgs.delta
    pkgs.fzf
    pkgs.zsh-powerlevel10k
    pkgs.zsh-fzf-tab
    pkgs.zsh-autosuggestions
    pkgs.zsh-history-search-multi-word
    pkgs.zsh-fast-syntax-highlighting
  ];

  zsh.zinit = {
    enable = true;
    plugins = [
      {
        verb = "light";
        path = "${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k";
        ices = [ "depth\"1\"" ];
      }
      {
        verb = "light";
        path = "${zshFzfTabWithoutModule}";
      }
      {
        verb = "light";
        path = "${pkgs.zsh-autosuggestions}/share/zsh/plugins/zsh-autosuggestions";
        ices = [ "wait" "lucid" "atload\"!_zsh_autosuggest_start\"" ];
      }
      {
        verb = "light";
        path = "${pkgs.zsh-history-search-multi-word}/share/zsh/zsh-history-search-multi-word";
        ices = [ "wait\"1\"" "lucid" ];
      }
      {
        verb = "light";
        path = "${pkgs.zsh-fast-syntax-highlighting}/share/zsh/plugins/fast-syntax-highlighting";
        ices = [ "wait" "lucid" "atinit\"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay\"" ];
      }
    ];
  };

  shell.hook.entries = [
    # Powerlevel10k instant prompt (must load early for caching)
    {
      loader = "preload";
      priority = 5;
      source = "${../config/powerlevel10k}/instant-prompt.zsh";
    }
    # Powerlevel10k main config (after powerlevel10k theme loads via zinit)
    {
      loader = "main";
      priority = 25;
      source = "${../config/powerlevel10k}/p10k.zsh";
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/zsh/envvar.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/zsh/option.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/zsh/keybind.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/lsd/aliases.sh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/delta/functions.sh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/claude/envvar.sh;
    }
    {
      loader = "main";
      priority = 60;
      source = ../config/fzf/envvar.sh;
    }
    {
      loader = "postload";
      priority = 90;
      source = ../config/direnv/hook.zsh;
    }
  ];

  home.file.".zshrc".text = ''
    # generated by home-manager

    # interactive only
    [[ -o interactive ]] || return

    # load shell hooks
    if [ -r "${config.xdg.configHome}/${config.shell.hook.scriptPath}" ]; then
      source "${config.xdg.configHome}/${config.shell.hook.scriptPath}"
    else
      printf 'failed to load shell hook script: not found: "%s" load error.\n' "${config.xdg.configHome}/${config.shell.hook.scriptPath}" >&2
    fi
  '';

  xdg.configFile."claude/CLAUDE.md" = {
    source = ../config/claude/CLAUDE.md;
  };
}
