{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.neovim
    pkgs.direnv
    pkgs.git
    pkgs.gh
    pkgs.uutils-coreutils-noprefix
    pkgs.lsd
    pkgs.bat
    pkgs.fd
    pkgs.delta
    pkgs.fzf
    pkgs.zsh-powerlevel10k
    pkgs.zsh-autosuggestions
    pkgs.zsh-history-search-multi-word
    pkgs.zsh-fast-syntax-highlighting
  ];

  zsh.zinit = {
    enable = true;
    plugins = [
      {
        verb = "light";
        path = "${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k";
        ices = [ "depth\"1\"" ];
      }
      {
        verb = "snippet";
        path = "${pkgs.fzf}/share/fzf/completion.zsh";
        ices = [ ];
      }
      {
        verb = "load";
        path = "${config.zinit.packages.fzf-tab-compat}";
        ices = [ "wait" "lucid" "blockf" ];
      }
      {
        verb = "light";
        path = "${pkgs.zsh-autosuggestions}/share/zsh/plugins/zsh-autosuggestions";
        ices = [ "wait" "lucid" "atload\"!_zsh_autosuggest_start\"" ];
      }
      {
        verb = "light";
        path = "${pkgs.zsh-history-search-multi-word}/share/zsh/zsh-history-search-multi-word";
        ices = [ "wait\"1\"" "lucid" ];
      }
      {
        verb = "light";
        path = "${pkgs.zsh-fast-syntax-highlighting}/share/zsh/plugins/fast-syntax-highlighting";
        ices = [ "wait" "lucid" "atinit\"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay\"" ];
      }
    ];
  };

  shell.hook.entries = [
    # Powerlevel10k instant prompt (must load early for caching)
    {
      loader = "preload";
      priority = 5;
      source = "${../config/powerlevel10k}/instant-prompt.zsh";
    }
    # Powerlevel10k main config (after powerlevel10k theme loads via zinit)
    {
      loader = "main";
      priority = 25;
      source = "${../config/powerlevel10k}/p10k.zsh";
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/zsh/envvar.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/zsh/option.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/zsh/keybind.zsh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/lsd/aliases.sh;
    }
    {
      loader = "main";
      priority = 50;
      source = ../config/delta/functions.sh;
    }
    {
      loader = "main";
      priority = 60;
      source = ../config/fzf/envvar.sh;
    }
    {
      loader = "main";
      priority = 70;
      source = ../config/fzf-tab/completion.zsh;
    }
    {
      loader = "postload";
      priority = 90;
      source = ../config/direnv/hook.zsh;
    }
  ];

  home.file.".zshrc".text = ''
    # generated by home-manager

    # interactive only
    [[ -o interactive ]] || return

    # load shell hooks
    if [ -r "${config.xdg.configHome}/${config.shell.hook.scriptPath}" ]; then
      source "${config.xdg.configHome}/${config.shell.hook.scriptPath}"
    else
      printf 'failed to load shell hook script: not found: "%s" load error.\n' "${config.xdg.configHome}/${config.shell.hook.scriptPath}" >&2
    fi
  '';
}
