# Loader for layered powerlevel10k configuration
# Architecture: base (defaults) → custom (overrides)
#
# Files:
#   - p10k-base.zsh:   Generated base configuration (regenerate on p10k upgrades)
#   - p10k-custom.zsh: User customizations (preserved across upgrades)
#   - p10k.zsh:        This loader (sources base → custom in correct scope)
#
# Upgrade workflow:
#   1. Run `p10k configure` to generate new base
#   2. Review diff: `diff -u p10k-base.zsh p10k-base-NEW.zsh`
#   3. Update p10k-custom.zsh if needed (adapt to renamed/deprecated options)
#   4. Replace base: `mv p10k-base-NEW.zsh p10k-base.zsh`
#   5. Test in new shell
#
# Hot reload: `source ~/.config/zsh/hook/p10k.zsh` (or wherever this loader is placed)

# Capture script directory before changing options
typeset -g __p10k_cfg_dir="${${(%):-%x}:A:h}"

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Load base configuration (generated by p10k configure)
  # Contains default settings from the lean theme
  source "$__p10k_cfg_dir/p10k-base.zsh"

  # Apply user customizations (overrides base values)
  # Later typeset statements overwrite earlier ones in the same scope
  source "$__p10k_cfg_dir/p10k-custom.zsh"
}

# Tell `p10k configure` which file it should overwrite.
# Point to base so custom is preserved.
typeset -g POWERLEVEL9K_CONFIG_FILE="$__p10k_cfg_dir/p10k-base.zsh"

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
'builtin' 'unset' '__p10k_cfg_dir'
